-- MySQL Script generated by MySQL Workbench
-- Thu Aug 26 06:57:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `cod_pessoa` INT NOT NULL,
  `nome` VARCHAR(200) NULL,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`cod_pessoa`),
  UNIQUE INDEX `cod_pessoa_UNIQUE` (`cod_pessoa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fabrincante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fabrincante` (
  `cod_fabricante` INT NOT NULL AUTO_INCREMENT,
  `nome_fabrincante` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_fabricante`),
  UNIQUE INDEX `nome_fabrincante_UNIQUE` (`nome_fabrincante` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo_veiculo` (
  `cod_modelo` INT NOT NULL AUTO_INCREMENT,
  `descricao_modelo` VARCHAR(45) NULL,
  `cod_fabricante` INT NOT NULL,
  PRIMARY KEY (`cod_modelo`),
  UNIQUE INDEX `descricao_modelo_UNIQUE` (`descricao_modelo` ASC) VISIBLE,
  INDEX `fk_modelo_veiculo_fabrincante_idx` (`cod_fabricante` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_veiculo_fabrincante`
    FOREIGN KEY (`cod_fabricante`)
    REFERENCES `mydb`.`fabrincante` (`cod_fabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda_veiculo` (
  `cod_venda` INT NOT NULL,
  `data_venda` DATE NULL,
  `valor_venda` DECIMAL NULL,
  `cod_pessoa` INT NOT NULL,
  `cod_modelo` INT NOT NULL,
  INDEX `fk_venda_veiculo_pessoa1_idx` (`cod_pessoa` ASC) VISIBLE,
  INDEX `fk_venda_veiculo_modelo_veiculo1_idx` (`cod_modelo` ASC) VISIBLE,
  CONSTRAINT `fk_venda_veiculo_pessoa1`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `mydb`.`pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_veiculo_modelo_veiculo1`
    FOREIGN KEY (`cod_modelo`)
    REFERENCES `mydb`.`modelo_veiculo` (`cod_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
